# Generated by Django 4.2.16 on 2025-02-05 20:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volume",
            options={
                "ordering": ["ml"],
                "verbose_name": "Volume",
                "verbose_name_plural": "Volumes",
            },
        ),
        migrations.RemoveField(
            model_name="productvolume",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="productvolume",
            name="image",
        ),
        migrations.RemoveField(
            model_name="productvolume",
            name="price",
        ),
        migrations.AddField(
            model_name="volume",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Cost Price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volume",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Selling Price"
            ),
            preserve_default=False,
        ),
    ]
