# Generated by Django 4.2.16 on 2025-02-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_volume_options_remove_productvolume_cost_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="volume",
            table="volume_details",
        ),
    ]
