# Generated by Django 4.2.16 on 2025-02-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_volume_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvolume",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("", "-- Choose product type --"),
                    ("Roll-On", "Roll-On"),
                    ("Spray", "Spray"),
                    ("Diffuser", "Diffuser"),
                ],
                default="Spray",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
