# Generated by Django 4.2.16 on 2025-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvolume",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("percentage", "Percentage"), ("fixed", "Fixed")],
                max_length=10,
                null=True,
                verbose_name="Discount Type",
            ),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Discount Value",
            ),
        ),
    ]
