# Generated by Django 4.2.16 on 2025-03-05 11:53

import apps.products.models
import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productvolume_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    apps.products.models.validate_image_size,
                ],
                verbose_name="image",
            ),
        ),
    ]
