# Generated by Django 4.2.16 on 2025-01-12 19:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productvolume_discount_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvolume",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
