# Generated by Django 4.2.16 on 2025-01-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productvolume_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvolume",
            name="discount_type",
        ),
    ]
