# Generated by Django 4.2.20 on 2025-05-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_review_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
    ]
