# Generated by Django 4.2.20 on 2025-05-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_product_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="updated_at",
        ),
    ]
