# Generated by Django 4.2.20 on 2025-08-01 19:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
