# Generated by Django 4.2.15 on 2026-05-28 21:27

import cloudinary.models
from django.db import migrations, models
from django.utils.text import slugify


def _unique_value(model, field_name, base_value, pk=None):
    base = slugify(base_value or "") or "item"
    value = base
    counter = 2
    queryset = model.objects.filter(**{field_name: value})
    if pk:
        queryset = queryset.exclude(pk=pk)
    while queryset.exists():
        value = f"{base}-{counter}"
        counter += 1
        queryset = model.objects.filter(**{field_name: value})
        if pk:
            queryset = queryset.exclude(pk=pk)
    return value


def backfill_product_metadata(apps, schema_editor):
    Category = apps.get_model("products", "Category")
    Product = apps.get_model("products", "Product")
    ProductImage = apps.get_model("products", "ProductImage")
    ProductVolume = apps.get_model("products", "ProductVolume")

    for category in Category.objects.filter(slug=""):
        category.slug = _unique_value(Category, "slug", category.name, category.pk)
        category.save(update_fields=["slug"])

    for product in Product.objects.filter(slug=""):
        product.slug = _unique_value(Product, "slug", product.name, product.pk)
        product.save(update_fields=["slug"])

    for image in ProductImage.objects.select_related("product").filter(alt_text=""):
        image.alt_text = image.product.name
        image.save(update_fields=["alt_text"])

    for variant in ProductVolume.objects.select_related("product", "volume").filter(
        name=""
    ):
        variant.name = f"{variant.product_type} - {variant.volume.ml}ML"
        variant.save(update_fields=["name"])

    used_skus = set(
        ProductVolume.objects.exclude(sku="").values_list("sku", flat=True)
    )
    for variant in ProductVolume.objects.select_related("product").filter(sku=""):
        product_code = slugify(variant.product.name or "product").upper()[:16]
        variant_code = slugify(variant.name or "variant").upper()[:16]
        base_sku = f"JBL-{product_code}-{variant_code}".replace(" ", "-")
        sku = base_sku
        counter = 2
        while sku in used_skus:
            sku = f"{base_sku}-{counter}"
            counter += 1
        used_skus.add(sku)
        variant.sku = sku
        variant.save(update_fields=["sku"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("products", "0012_alter_product_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.AlterModelOptions(
            name="productvolume",
            options={
                "ordering": ["sort_order", "volume__ml", "product_type"],
                "verbose_name": "Product Volume",
                "verbose_name_plural": "Product Volumes",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hero_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="hero image"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="max_quantity_per_order",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Customer-facing variant name. Defaults to type and volume.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional selling price override for this product variant.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="sku",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank to keep legacy untracked-stock behavior.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional cost override for this product variant.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_product_metadata, noop_reverse),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_featured"], name="product_status_8741e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="product_slug_b8980b_idx"),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(
                fields=["product", "is_active"], name="products_pr_product_63dbeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(fields=["sku"], name="products_pr_sku_b6be85_idx"),
        ),
    ]
