# Generated by Django 4.2.15 on 2026-05-30 17:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="productvolume",
            options={
                "ordering": ["sort_order", "volume__ml", "product_type", "name"],
                "verbose_name": "Product Variation",
                "verbose_name_plural": "Product Variations",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="product_slug_idx",
            old_name="product_slug_b8980b_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="product_status_featured_idx",
            old_name="product_status_8741e6_idx",
        ),
        migrations.RenameIndex(
            model_name="productvolume",
            new_name="variant_product_active_idx",
            old_name="products_pr_product_63dbeb_idx",
        ),
        migrations.RenameIndex(
            model_name="productvolume",
            new_name="variant_sku_idx",
            old_name="products_pr_sku_b6be85_idx",
        ),
        migrations.AlterUniqueTogether(
            name="productvolume",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="category_image"
            ),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra variation attributes such as material, pack size, or label.",
            ),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="barcode",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Optional color/shade variation, e.g. Black, Red, Gold.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="scent",
            field=models.CharField(
                blank=True,
                help_text="Optional scent/fragrance variation.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Optional non-volume size variation, e.g. Small, Medium, Large.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="productvolume",
            name="variant_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="variant image"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=256, verbose_name="Product Name"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="category_name_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="category_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "name"], name="category_active_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="product_name_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["uuid"], name="product_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status"], name="product_status_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="product_category_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["supplier", "status"], name="product_supplier_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["gender", "status"], name="product_gender_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["created_at"], name="product_created_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["product"], name="product_image_product_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_active"], name="product_image_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_default"], name="product_image_default_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["sort_order", "created_at"], name="product_image_sort_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(fields=["product"], name="variant_product_idx"),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(fields=["volume"], name="variant_volume_idx"),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(
                fields=["product", "volume", "product_type"],
                name="variant_product_combo_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(fields=["barcode"], name="variant_barcode_idx"),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(fields=["product_type"], name="variant_type_idx"),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(
                fields=["is_active", "stock_quantity"], name="variant_active_stock_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(fields=["price"], name="variant_price_idx"),
        ),
        migrations.AddIndex(
            model_name="productvolume",
            index=models.Index(fields=["sort_order"], name="variant_sort_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["product"], name="review_product_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user"], name="review_user_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "is_verified"], name="review_product_verified_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="review_rating_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["created_at"], name="review_created_idx"),
        ),
        migrations.AddIndex(
            model_name="volume",
            index=models.Index(fields=["ml"], name="volume_ml_idx"),
        ),
        migrations.AddIndex(
            model_name="volume",
            index=models.Index(fields=["price"], name="volume_price_idx"),
        ),
        migrations.AddIndex(
            model_name="volume",
            index=models.Index(fields=["cost"], name="volume_cost_idx"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="unique_category_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="unique_product_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvolume",
            constraint=models.UniqueConstraint(
                fields=("product", "volume", "product_type", "color", "size", "scent"),
                name="unique_product_variation",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvolume",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("sku",),
                name="unique_product_variation_sku",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvolume",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("barcode",),
                name="unique_product_variation_barcode",
            ),
        ),
        migrations.AlterModelTable(
            name="review",
            table="product_review",
        ),
    ]
