# Generated by Django 4.2.15 on 2026-05-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0014_alter_category_options_alter_productvolume_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productvolume",
            name="unique_product_variation_barcode",
        ),
        migrations.RemoveIndex(
            model_name="productimage",
            name="product_image_product_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvolume",
            name="variant_product_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvolume",
            name="variant_volume_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="review_product_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="review_user_idx",
        ),
        migrations.AddConstraint(
            model_name="productvolume",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("barcode",),
                name="uniq_variant_barcode",
            ),
        ),
    ]
