# Generated by Django 4.2.15 on 2026-06-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0015_remove_productvolume_unique_product_variation_barcode_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvolume",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("", "-- Choose product type --"),
                    ("Roll-On", "Roll-On"),
                    ("Spray", "Spray"),
                    ("Diffuser", "Diffuser"),
                    ("Mini", "Mini"),
                ],
                default="Spray",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
