# Generated by Django 4.2.15 on 2026-06-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_productvolume_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvolume",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("", "-- Choose variant type --"),
                    ("Mini", "Mini"),
                    ("Roll-On", "Roll-On"),
                    ("Spray", "Spray"),
                    ("Diffuser", "Diffuser"),
                ],
                default="Spray",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
