# Generated by Django 4.2.16 on 2025-02-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_volume_table"),
        ("orders", "0002_orderdetail_discounted_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="product_volume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.productvolume"
            ),
        ),
    ]
