# Generated by Django 4.2.16 on 2025-02-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productvolume_product_type"),
        ("orders", "0004_alter_orderdetail_product_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="product_volume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.productvolume"
            ),
        ),
    ]
