# Generated by Django 4.2.16 on 2025-02-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_orderdetail_product_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                    ("Refunded", "Refunded"),
                    ("Returned", "Returned"),
                ],
                max_length=20,
            ),
        ),
    ]
