# Generated by Django 4.2.20 on 2025-06-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_cartitem_created_at_cartitem_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="updated_at",
        ),
    ]
