# Generated by Django 4.2.20 on 2025-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_cartitem_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
