# Generated by Django 4.2.20 on 2025-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_cart_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
