# Generated by Django 4.2.20 on 2025-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_cart_session_key_alter_cart_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cod", "Cash on Delivery"), ("mobile", "Mobile Money")],
                default="cod",
                max_length=20,
            ),
        ),
    ]
