# Generated by Django 4.2.15 on 2026-05-30 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0014_alter_category_options_alter_productvolume_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "customers",
            "0005_alter_customer_options_customer_customer_email_idx_and_more",
        ),
        ("orders", "0014_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="orderdetail",
            options={"ordering": ["order_id", "id"]},
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Session key for anonymous users",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                    ("Refunded", "Refunded"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlisted_by",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["user", "updated_at"], name="cart_user_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["session_key"], name="cart_session_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["updated_at"], name="cart_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product"], name="cartitem_cart_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["volume"], name="cartitem_volume_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["updated_at"], name="cartitem_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "created_at"], name="order_customer_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="order_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status", "created_at"], name="ord_paystat_cr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_method", "created_at"], name="ord_paymeth_cr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="order_created_idx"),
        ),
        migrations.AddIndex(
            model_name="orderdetail",
            index=models.Index(
                fields=["order", "product"], name="orderdetail_order_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdetail",
            index=models.Index(
                fields=["product_volume"], name="orderdetail_variant_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdetail",
            index=models.Index(
                fields=["product", "created_at"], name="odet_prod_cr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["user", "added_at"], name="wishlist_user_added_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["product", "added_at"], name="wishlist_product_added_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "volume"), name="unique_cart_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product_wishlist"
            ),
        ),
    ]
