# Generated by Django 4.2.15 on 2026-05-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cartitem_volume_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderdetail",
            name="orderdetail_variant_idx",
        ),
    ]
