# Generated by Django 4.2.15 on 2026-05-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_remove_cartitem_cartitem_volume_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mobile_money_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
