# Generated by Django 4.2.15 on 2026-06-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
        ("orders", "0017_order_mobile_money_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_region",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shipping.pickupstation",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[("delivery", "Door Delivery"), ("pickup", "Pickup Station")],
                db_index=True,
                default="delivery",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["shipping_method", "created_at"], name="ord_shipmeth_cr_idx"
            ),
        ),
    ]
