# Generated by Django 4.2.15 on 2026-06-10 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0018_order_delivery_address_text_order_delivery_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("flutterwave", "Flutterwave"),
                            ("mobile_money", "Mobile Money"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=10)),
                (
                    "transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_order_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "created_at"], name="ordpay_order_created_idx"
                    ),
                    models.Index(
                        fields=["provider", "created_at"], name="ordpay_provider_cr_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="orderpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_id", ""), _negated=True),
                fields=("provider", "transaction_id"),
                name="uniq_order_payment_provider_tx",
            ),
        ),
    ]
