# Generated by Django 4.2.15 on 2026-06-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_orderpayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                    ("Refunded", "Refunded"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
