# Generated by Django 4.2.20 on 2025-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("mobile_money", "Mobile Money"),
                    ("cheque", "Cheque"),
                    ("other", "Other"),
                ],
                default="CASH",
                max_length=50,
            ),
        ),
    ]
