# Generated by Django 4.2.15 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_sale_payment_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={"ordering": ["-trans_date", "-id"]},
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["order"], name="sale_order_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer", "trans_date"], name="sale_customer_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["trans_date"], name="sale_trans_date_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["payment_method", "trans_date"], name="sale_payment_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["sale_type", "trans_date"], name="sale_type_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["receipt_number"], name="sale_receipt_idx"),
        ),
        migrations.AddIndex(
            model_name="saledetail",
            index=models.Index(
                fields=["sale", "product"], name="saledetail_sale_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saledetail",
            index=models.Index(
                fields=["product_volume"], name="saledetail_variant_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saledetail",
            index=models.Index(
                fields=["product", "created_at"], name="saledetail_product_created_idx"
            ),
        ),
    ]
