# Generated by Django 4.2.15 on 2026-05-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_sale_options_sale_sale_order_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sale",
            name="sale_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="saledetail",
            name="saledetail_variant_idx",
        ),
        migrations.RenameIndex(
            model_name="saledetail",
            new_name="saledetail_prod_cr_idx",
            old_name="saledetail_product_created_idx",
        ),
    ]
