# Generated by Django 4.2.20 on 2025-09-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customer_mobile_alter_customer_tel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Shipping Address"
            ),
        ),
    ]
