# Generated by Django 4.2.15 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_customer_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customer_email_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["first_name", "last_name"], name="customer_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["created_at"], name="customer_created_idx"),
        ),
    ]
