# Generated by Django 4.2.20 on 2025-07-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_branch_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialperiod",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
