# Generated by Django 4.2.20 on 2025-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_financialperiod_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
