# Generated by Django 4.2.20 on 2025-07-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_transaction_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="description",
        ),
        migrations.RemoveField(
            model_name="financialperiod",
            name="description",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="description",
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Narration"),
        ),
    ]
