# Generated by Django 4.2.20 on 2025-07-31 12:08


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_remove_branch_description_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE finance_journalentry
            DROP CONSTRAINT valid_payment_method;
            """,
            reverse_sql="""
            ALTER TABLE finance_journalentry
            ADD CONSTRAINT valid_payment_method
            CHECK (payment_method IN ('cash', 'bank_transfer', 'check', 'mobile_payment') OR payment_method IS NULL);
            """,
        ),
    ]
