# Generated by Django 4.2.15 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_auto_20250731_1508"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "ordering": ["name"],
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.AlterModelOptions(
            name="journalentry",
            options={"ordering": ["-transaction_date", "-id"]},
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["code"], name="branch_code_idx"),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(
                fields=["account_number"], name="coa_account_number_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(
                fields=["account_type", "status"], name="coa_type_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(
                fields=["branch", "status"], name="coa_branch_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(fields=["parent_account"], name="coa_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(
                fields=["is_deleted", "status"], name="coa_deleted_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialperiod",
            index=models.Index(
                fields=["branch", "status"], name="period_branch_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="period_date_range_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialperiod",
            index=models.Index(
                fields=["status", "start_date"], name="period_status_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["reference_number"], name="journal_reference_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["transaction_date"], name="journal_date_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["financial_period", "transaction_date"],
                name="journal_period_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["branch", "transaction_date"], name="journal_branch_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["payment_method"], name="journal_payment_method_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["journal_entry", "transaction_type"],
                name="txn_journal_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "transaction_type"], name="txn_account_type_idx"
            ),
        ),
    ]
