# Generated by Django 4.2.15 on 2026-06-01 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "street_name",
                    models.CharField(
                        max_length=255,
                        verbose_name="Street Name / Building Number / Apartment",
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("area", models.CharField(blank=True, db_index=True, max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("additional_telephone", models.CharField(blank=True, max_length=20)),
                ("additional_information", models.TextField(blank=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("kampala_area", "Kampala Area"),
                            ("entebbe_area", "Entebbe Area"),
                            ("central_region", "Central Region"),
                            ("eastern_region", "Eastern Region"),
                            ("northern_region", "Northern Region"),
                            ("western_region", "Western Region"),
                            ("rest_of_kampala", "Rest of Kampala"),
                        ],
                        db_index=True,
                        default="kampala_area",
                        max_length=30,
                    ),
                ),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-is_default", "-created_at"],
                        name="addresses_c_user_id_731f88_idx",
                    ),
                    models.Index(
                        fields=["user", "city"], name="addresses_c_user_id_34b1a6_idx"
                    ),
                    models.Index(fields=["user", "area"], name="address_user_area_idx"),
                    models.Index(
                        fields=["user", "region"], name="addresses_c_user_id_2c56b0_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customeraddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="unique_default_address_per_user",
            ),
        ),
    ]
