# Generated by Django 4.2.15 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventory_created_at_inventory_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ["product__name"]},
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["quantity"], name="inventory_quantity_idx"),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["is_out_of_stock", "quantity"],
                name="inventory_stock_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["updated_at"], name="inventory_updated_idx"),
        ),
    ]
