# Generated by Django 4.2.15 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["name"]},
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["name"], name="supplier_name_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["email"], name="supplier_email_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["created_at"], name="supplier_created_idx"),
        ),
    ]
