# Generated by Django 4.2.15 on 2026-06-01 20:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PickupStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("opening_hours", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["city", "area", "name"],
                "indexes": [
                    models.Index(
                        fields=["city", "area"], name="shipping_pi_city_c1cc56_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="shipping_pi_is_acti_445840_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("kampala_area", "Kampala Area"),
                            ("entebbe_area", "Entebbe Area"),
                            ("central_region", "Central Region"),
                            ("eastern_region", "Eastern Region"),
                            ("northern_region", "Northern Region"),
                            ("western_region", "Western Region"),
                            ("rest_of_kampala", "Rest of Kampala"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("city", models.CharField(blank=True, db_index=True, max_length=100)),
                ("area", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("estimated_days", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["region", "city", "area", "fee", "estimated_days", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="shipping_de_is_acti_8cc362_idx"
                    ),
                    models.Index(
                        fields=["region", "city", "area"],
                        name="shipping_de_region_246e5d_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="deliveryrate",
            constraint=models.UniqueConstraint(
                fields=("region", "city", "area"),
                name="unique_delivery_rate_per_location",
            ),
        ),
    ]
