# Generated by Django 4.2.16 on 2025-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
