# Generated by Django 4.2.16 on 2025-02-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_newslettersubscriber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsletterSubscriber",
        ),
    ]
