# Generated by Django 4.2.16 on 2025-02-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="consent",
            field=models.BooleanField(default=False, verbose_name="Email Consent"),
        ),
    ]
