# Generated by Django 4.2.15 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_subscriber_consent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(fields=["email"], name="subscriber_email_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(
                fields=["consent", "created_at"], name="subscriber_consent_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["approved", "created_at"], name="test_appr_cr_idx"
            ),
        ),
    ]
