# Generated by Django 4.2.15 on 2026-05-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_subscriber_options_alter_testimonial_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subscriber",
            new_name="sub_consent_cr_idx",
            old_name="subscriber_consent_created_idx",
        ),
    ]
