# Generated by Django 4.2.15 on 2026-06-12 06:22

from django.db import migrations, models
import django.db.models.functions.text


def normalize_subscriber_emails(apps, schema_editor):
    Subscriber = apps.get_model("main", "Subscriber")
    seen = {}
    duplicates = []

    for subscriber in Subscriber.objects.order_by("created_at", "id"):
        normalized = (subscriber.email or "").strip().lower()
        if not normalized:
            continue

        existing_id = seen.get(normalized)
        if existing_id:
            existing = Subscriber.objects.get(pk=existing_id)
            updates = []
            if subscriber.consent and not existing.consent:
                existing.consent = True
                updates.append("consent")
            if updates:
                existing.save(update_fields=updates)
            duplicates.append(subscriber.pk)
            continue

        seen[normalized] = subscriber.pk
        if subscriber.email != normalized:
            subscriber.email = normalized
            subscriber.save(update_fields=["email"])

    if duplicates:
        Subscriber.objects.filter(pk__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_subscriber_consent_created_idx_sub_consent_cr_idx"),
    ]

    operations = [
        migrations.RunPython(normalize_subscriber_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="subscriber",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="subscriber_email_ci_unique",
            ),
        ),
    ]
