# Generated by Django 4.2.16 on 2025-01-18 19:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_profile_mobile_profile_tel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="+12125552368",
                max_length=16,
                null=True,
                region=None,
                verbose_name="Mobile",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tel",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="+12125552368",
                max_length=16,
                null=True,
                region=None,
                verbose_name="Telephone",
            ),
        ),
    ]
