# Generated by Django 4.2.16 on 2025-02-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_profile_mobile_alter_profile_tel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(max_length=100, verbose_name="Message"),
        ),
    ]
