# Generated by Django 4.2.16 on 2025-02-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterModelTable(
            name="contact",
            table="feedback",
        ),
    ]
