# Generated by Django 4.2.16 on 2025-02-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_contact_message_alter_contact_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
