# Generated by Django 4.2.20 on 2025-06-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("authentication", "0007_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="finance.branch",
                verbose_name="Branch",
            ),
        ),
    ]
