# Generated by Django 4.2.20 on 2025-07-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_profile_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="branch",
        ),
    ]
